import type { Word } from "@/types";

/** 内嵌种子单词库 — 图片统一使用 WebP 格式，体积压缩 95%+ */
export const seedWords: Word[] = [
  { word: "Alligator", image: "img/alligator.webp" },
  { word: "Animals", image: "img/animals.webp" },
  { word: "Ant", image: "img/ant.webp" },
  { word: "Apple", image: "img/apple.webp" },
  { word: "Ax", image: "img/ax.webp" },
  { word: "Banana", image: "img/banana.webp" },
  { word: "Bear", image: "img/bear.webp" },
  { word: "Bed", image: "img/bed.webp" },
  { word: "Bird", image: "img/bird.webp" },
  { word: "Boy", image: "img/boy.webp" },
  { word: "Bunny", image: "img/bunny.webp" },
  { word: "Car", image: "img/car.webp" },
  { word: "Cat", image: "img/cat.webp" },
  { word: "Chicken", image: "img/chicken.webp" },
  { word: "Computer", image: "img/computer.webp" },
  { word: "Cow", image: "img/cow.webp" },
  { word: "Cup", image: "img/cup.webp" },
  { word: "Deer", image: "img/deer.webp" },
  { word: "Dog", image: "img/dog.webp" },
  { word: "Duck", image: "img/duck.webp" },
  { word: "Fox", image: "img/fox.webp" },
  { word: "Girl", image: "img/girl.webp" },
  { word: "Goat", image: "img/goat.webp" },
  { word: "Goldfish", image: "img/goldfish.webp" },
  { word: "Hamster", image: "img/hamster.webp" },
  { word: "Horse", image: "img/horse.webp" },
  { word: "Mouse", image: "img/mouse.webp" },
  { word: "Pig", image: "img/pig.webp" },
  { word: "Sheep", image: "img/sheep.webp" },
  { word: "Turtle", image: "img/turtle.webp" },
  { word: "Elephant", image: "img/elephant.webp" },
];
